server:
  port: 7777
spring:
  application:
    name: source-samples
  ##### rabbitmq 服务配置 #####
  rabbitmq:
    host: 106.12.95.51
    port: 5672
    username: chenjian
    password: 123456
    virtual-host: /
  cloud:
    ##### spring cloud stream 配置 #####
    stream:
      # 默认 binder
      defaultBinder: rabbit
      bindings:
        test-output:
          # 指定 binder
#          binder: rabbit
          destination: testExchange
          content-type: application/json
          producer:
            # 指定参与消息分区的消费端节点数量为2个
            partitionCount: 2
            # 表示只有分区ID为1的消费端能接收到信息，这里可以自定义分区策略
            partitionKeyExpression: payload.id % ${spring.cloud.stream.bindings.test-output.producer.partitionCount}
        test-input:
          destination: testExchange2
          group: testQueue2
        rocket-output:
          binder: rocket
      # 配置多个消息队列服务
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 106.12.95.51
#                port: 5672
#                username: chenjian
#                password: 123456
#                virtual-host: /